## Projeto Sprint 8 - Análise de Negócio

### Contexto do Projeto
Trabalhamos no departamento analítico da Y.Afisha e fomos encarregados de otimizar os investimentos em marketing da empresa. Para isso, precisamos entender melhor o perfil dos consumidores e a eficiência dos diferentes canais de aquisição.

### Objetivo
Analisar os dados de janeiro de 2017 a dezembro de 2018 para otimizar os gastos com marketing e maximizar o retorno sobre investimento (ROI).

### Perguntas de Negócio
Este projeto busca responder às seguintes questões estratégicas:
* Qual é o perfil do nosso consumidor?
* Por quais canais de marketing nossos clientes chegam até nós?
* Quando os usuários começam a fazer compras após o primeiro acesso?
* Qual é o retorno sobre investimento (ROI) dos nossos canais de marketing?
* Quanto tempo demora para recuperar o investimento em aquisição de clientes?
* Qual canal oferece o melhor custo-benefício para futuros investimentos?

In [1]:
# Bibliotecas
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns   
import numpy as np
import requests
import io

In [2]:
#Importando os dados de visitas já com a conversão nas colunas referentes a Start Ts e End Ts de (object -> datetime).
# Convertendo a coluna Device para 'category' visto que só temos 2 categorias (Touch e Desktop).

visits = pd.read_csv('visits_log_us.csv', 
                     parse_dates=['Start Ts', 'End Ts'], 
                     dtype={'Device': 'category'})

In [3]:
#importando os dados de vendas(order) já com a conversão na coluna Buy Ts de (object -> datetime).
order = pd.read_csv('orders_log_us.csv',
                     parse_dates=['Buy Ts'])

In [4]:
#Importando os dados de custos(costs) já com a conversão na coluna Dt de (object -> datetime).
costs = pd.read_csv('costs_us.csv',
                     parse_dates=['dt'])

## Análisando os DataFrames

In [5]:
#Analisando os dados de visitas
visits.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 359400 entries, 0 to 359399
Data columns (total 5 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   Device     359400 non-null  category
 1   End Ts     359400 non-null  datetime64[ns]
 2   Source Id  359400 non-null  int64
 3   Start Ts   359400 non-null  datetime64[ns]
 4   Uid        359400 non-null  uint64
dtypes: category(1), datetime64[ns](2), int64(1), uint64(1)
memory usage: 11.3 MB

In [6]:
#Observando os dados de visitas(visits).
visits.head()

,Device,End Ts,Source Id,Start Ts,Uid
0,touch,2017-12-20 17:38:00,4,2017-12-20 17:20:00,16879256277535980062
1,desktop,2018-02-19 17:21:00,2,2018-02-19 16:53:00,104060357244891740
2,touch,2017-07-01 01:54:00,5,2017-07-01 01:54:00,7459035603376831527
3,desktop,2018-05-20 11:23:00,9,2018-05-20 10:59:00,16174680259334210214
4,desktop,2017-12-27 14:06:00,3,2017-12-27 14:06:00,9969694820036681168

In [7]:
#Contando quantos dados temos para cada categoria da coluna Device.
visits['Device'].value_counts()

Device
desktop    262567
touch       96833
Name: count, dtype: int64

In [8]:
#Analisando os dados de vendas(order).
order.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50415 entries, 0 to 50414
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Buy Ts   50415 non-null  datetime64[ns]
 1   Revenue  50415 non-null  float64
 2   Uid      50415 non-null  uint64
dtypes: datetime64[ns](1), float64(1), uint64(1)
memory usage: 1.2 MB

In [ ]:
#Observando os dados de vendas(order).
order.head()

               Buy Ts  Revenue                   Uid
0 2017-06-01 00:10:00    17.00  10329302124590727494
1 2017-06-01 00:25:00     0.55  11627257723692907447
2 2017-06-01 00:27:00     0.37  17903680561304213844
3 2017-06-01 00:29:00     0.55  16109239769442553005
4 2017-06-01 07:58:00     0.37  14200605875248379450

In [9]:
#Analisando os dados de custos(costs).
costs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2542 entries, 0 to 2541
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   source_id  2542 non-null   int64
 1   dt         2542 non-null   datetime64[ns]
 2   costs      2542 non-null   float64
dtypes: datetime64[ns](1), float64(1), int64(1)
memory usage: 59.7 KB

In [12]:
costs.head()

   source_id         dt  costs
0          1 2017-06-01  75.20
1          1 2017-06-02  62.25
2          1 2017-06-03  36.53
3          1 2017-06-04  55.00
4          1 2017-06-05  57.08